//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youtube_dl_gui.Configurations {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Batch : global::System.Configuration.ApplicationSettingsBase {
        
        private static Batch defaultInstance = ((Batch)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Batch())));
        
        public static Batch Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SelectedType {
            get {
                return ((int)(this["SelectedType"]));
            }
            set {
                this["SelectedType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedVideoQuality {
            get {
                return ((int)(this["SelectedVideoQuality"]));
            }
            set {
                this["SelectedVideoQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedVideoFormat {
            get {
                return ((int)(this["SelectedVideoFormat"]));
            }
            set {
                this["SelectedVideoFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedAudioQuality {
            get {
                return ((int)(this["SelectedAudioQuality"]));
            }
            set {
                this["SelectedAudioQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedAudioFormat {
            get {
                return ((int)(this["SelectedAudioFormat"]));
            }
            set {
                this["SelectedAudioFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DownloadVideoSound {
            get {
                return ((bool)(this["DownloadVideoSound"]));
            }
            set {
                this["DownloadVideoSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DownloadAudioVBR {
            get {
                return ((bool)(this["DownloadAudioVBR"]));
            }
            set {
                this["DownloadAudioVBR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedAudioQualityVBR {
            get {
                return ((int)(this["SelectedAudioQualityVBR"]));
            }
            set {
                this["SelectedAudioQualityVBR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomArguments {
            get {
                return ((string)(this["CustomArguments"]));
            }
            set {
                this["CustomArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClipboardScannerNoticeViewed {
            get {
                return ((bool)(this["ClipboardScannerNoticeViewed"]));
            }
            set {
                this["ClipboardScannerNoticeViewed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClipboardScannerVerifyLinks {
            get {
                return ((bool)(this["ClipboardScannerVerifyLinks"]));
            }
            set {
                this["ClipboardScannerVerifyLinks"] = value;
            }
        }
    }
}
