//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youtube_dl_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("youtube_dl_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AboutImage {
            get {
                object obj = ResourceManager.GetObject("AboutImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022-09-01.
        /// </summary>
        public static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap finished {
            get {
                object obj = ResourceManager.GetObject("finished", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;url&quot;: &quot;https://api.github.com/repos/murrty/youtube-dl-gui/releases/69835524&quot;,
        ///    &quot;assets_url&quot;: &quot;https://api.github.com/repos/murrty/youtube-dl-gui/releases/69835524/assets&quot;,
        ///    &quot;upload_url&quot;: &quot;https://uploads.github.com/repos/murrty/youtube-dl-gui/releases/69835524/assets{?name,label}&quot;,
        ///    &quot;html_url&quot;: &quot;https://github.com/murrty/youtube-dl-gui/releases/tag/2.31-pre2&quot;,
        ///    &quot;id&quot;: 69835524,
        ///    &quot;author&quot;: {
        ///      &quot;login&quot;: &quot;murrty&quot;,
        ///      &quot;id&quot;: 10895809,
        ///      &quot;node_id&quot;: &quot;MDQ6VXNlcjEwODk1OD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Git {
            get {
                return ResourceManager.GetString("Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ProgramIcon {
            get {
                object obj = ResourceManager.GetObject("ProgramIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap waiting {
            get {
                object obj = ResourceManager.GetObject("waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] youtube_dl_gui_updater {
            get {
                object obj = ResourceManager.GetObject("youtube_dl_gui_updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;: &quot;OX79nEdyzrc&quot;, &quot;title&quot;: &quot;Round 3: \&quot;Is Intel Actually Screwed?\&quot; Ft. Gordon of PC World&quot;, &quot;formats&quot;: [{&quot;format_id&quot;: &quot;sb2&quot;, &quot;format_note&quot;: &quot;storyboard&quot;, &quot;ext&quot;: &quot;mhtml&quot;, &quot;protocol&quot;: &quot;mhtml&quot;, &quot;acodec&quot;: &quot;none&quot;, &quot;vcodec&quot;: &quot;none&quot;, &quot;url&quot;: &quot;https://i.ytimg.com/sb/OX79nEdyzrc/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgj31c-YBg==&amp;sigh=rs$AOn4CLCaubvAiQtEVyPrBGb64LM02A_t-Q&quot;, &quot;width&quot;: 48, &quot;height&quot;: 27, &quot;fps&quot;: 0.07423904974016332, &quot;rows&quot;: 10, &quot;columns&quot;: 10, &quot;fragments&quot;: [{&quot;url&quot;: &quot;https://i.y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YtdlpTest {
            get {
                return ResourceManager.GetString("YtdlpTest", resourceCulture);
            }
        }
    }
}
